pre-release-commit-message = "chore({{crate_name}}): Release {{version}}"
no-dev-version = true
tag-message = "{{tag_name}}"
tag-name = "{{prefix}}v{{version}}"
pre-release-replacements = [
  {file="src/lib.rs", search="proc-exit = \".*\"", replace="proc-exit = \"{{version}}\""},
  {file="README.md", search="proc-exit = \".*\"", replace="proc-exit = \"{{version}}\""},
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}"},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate"},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/assert-rs/predicates-rs/compare/{{tag_name}}...HEAD"},
]
